INIT_PENALTY_PARM_X = 1
INIT_PENALTY_PARM_S = 1
PENALTY_MULTIPLIER = 0.7
MAX_ITERATION_NUM = 200
MAX_TERMINATE_S = 2
MAX_TOLERANCE_X = 0.1
MAX_TOLERANCE_S = 1.5

SCALER_PARM = 0.5
FIX_STEP_CONSTANT = 50
TERMINATE_PROP_PARM = 1E-4
TERMINATE_GAP_PARM = 1E-2
TERMINATE_REPLICATE_PARM = 20
MAX_UPDATE_NUM = 50

BigM = 1000000